export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: "/posts/post1.png",
		user: {
			username: "Salah eldin",
			profileImg: "/avatars/boy1.png",
			fullName: "Salah eldin",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "Rana elsayed",
					profileImg: "/avatars/girl1.png",
					fullName: "Rana elsayed",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "Mohamed Mahmoud",
			profileImg: "/avatars/boy2.png",
			fullName: "Mohamed Mahmoud",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "Radwa salah",
					profileImg: "/avatars/girl2.png",
					fullName: "Radwa salah",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/posts/post2.png",
		user: {
			username: "Kareem Rady",
			profileImg: "/avatars/boy3.png",
			fullName: "Kareem Rady",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "/posts/post3.png",
		user: {
			username: "Ahmed Mohamed",
			profileImg: "/avatars/boy3.png",
			fullName: "Ahmed Mohamed",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "Asmaa Yousef",
					profileImg: "/avatars/girl3.png",
					fullName: "Asmaa Yousef",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "Mohamed Mahmoud",
		username: "Mohamed2mahmoud",
		profileImg: "/avatars/boy2.png",
	},
	{
		_id: "2",
		fullName: "Asmaa Yousef",
		username: "Asmaa Yousef",
		profileImg: "/avatars/girl1.png",
	},
	{
		_id: "3",
		fullName: "Salah eldin",
		username: "Salah1011",
		profileImg: "/avatars/boy3.png",
	},
	{
		_id: "4",
		fullName: "Rana elsayed",
		username: "rana190",
		profileImg: "/avatars/girl2.png",
	},
];